### PR TITLE
Update ArrayType.php

### PR DESCRIPTION
**Pull request by xoeoro**
fix possibility use "$arrayModel[] = $item;" syntax

### CODE REVIEW

**Comment by kasperg** [comment]
Thanks for the suggestion @xoeoro. Could you please [update the ArrayType test](https://github.com/wsdl2phpgenerator/wsdl2phpgenerator/blob/master/tests/src/Unit/ArrayTypeTest.php#L89) so we also ensure that keyless setting work as expected?

**Comment by xoeoro** [comment]
Hi @kasperg 
just added commit 2926df5366ee18a76b05ca17dbe82066e3b1fb47 with modified test

**Comment by kasperg** [comment]
Great. Could you also please [squash your changes into a single commit](http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request)? Then we should be good to merge.

**Comment by xoeoro** [comment]
squashed

**Comment by kasperg** [comment]
Merged. Thanks for the contribution @xoeoro!

**Pull request merged**
