### PR TITLE
[WIP] Added support for generating public properties without accessors and constructor

### PR DESCRIPTION
**Pull request by lucasvanlierop**

### CODE REVIEW

**Comment by kasperg** [comment]
With 3.x wsdl2phpgenerator went from public properties to accessors. This was discussed in #106.

I do not want to waste your time and without some argumentation this will not go in. 

In general I am interested in keeping the number of configuration options low as this reduces the complexity of the code and makes maintenance easier.

**Comment by lucasvanlierop** [comment]
Ah ok, I was about to add documentation for this option. But I'm not in for arguing so I'll close this PR and just create our DTO's by hand.

FYI: the reason I'm in favor of public properties is that setters do not add much guarantee about the state of the object other than maybe a type in some caes. So I chose to either use a very plain PHP object (with public properties) for DTO's or immutable value objects for domain objects.

**Comment by kasperg** [comment]
Thanks for the follow up. I did not mean to be negative about your work.

If you are interested in this area I would be happy to discuss/look at a pull request for making the generator produce immutable value objects.

**Comment by lucasvanlierop** [comment]
No problem ;-) and sorry for the late reply, I was on Holiday (in Denmark btw). I will discuss it with our team, if we think our project benefits from it we we will make a new PR.

**Comment by kasperg** [comment]
Cool. Hope you enjoyed your holiday :).

**Pull request closed without merging**
