### PR TITLE
PHP 7.2 Support (incomplete)

### PR DESCRIPTION
**Pull request by ekeyte**
Good news, friends! I've finally found some time to upgrade the famous **wsdl2phpgenerator** page to work with PHP 7.2!

In order to get thing working, I've had to make a few upgrades:

- (Requested) upgrade to Symfony Options Resolver v4
- Upgrade to PhpUnit 6
- Upgrade php-vcr/phpunit-testlistener-vcr to ~3.0

We might consider tagging this as a release, since there could be breaking changes. In addition, I've had to make a few other changes:

- Removing the composer.lock file. That **absolutely should be versioned**.
- (not required), but I created a base Wsdl2PhpGenerator abstract test case which extends from `TestCase`. The old `PHPUnit_Framework_TestCase` was deprecated.
- I added a phpunit.xml default file.

image

P.S. @pierre-H asked for some changes in #332. These were made in this PR. The other one should be closed.

### CODE REVIEW

**Comment by uuf6429** [comment]
Hey, you can still support PHP 5.6 (and lower if desired) by applying these two changes:
- `require phpunit/phpunit "^7 || ^5"
- make your tests extend `CommonTestCase` which is defined as so:
   ```php
   if (class_exists(\PHPUnit\Framework\TestCase::class)) {
       // PHPUnit 6+
       class CommonTestCase extends \PHPUnit\Framework\TestCase
       {
       }
   } elseif (class_exists(\PHPUnit_Framework_TestCase::class)) {
       // PHPUnit 5
       class CommonTestCase extends \PHPUnit_Framework_TestCase
       {
       }
   } else {
       throw new RuntimeException('Unsupported PHPUnit version');
   }
   ```

Then you just need to be careful to use functionality common to both (eg; use `expectException()` instead of `setExpectedException()`).

**Comment by ekeyte** [comment]
Thanks @uuf6429 very nice catch! :)

I'm pretty new to contributing to libraries, so, nice trick to learn.

**Comment by localheinz** [comment]
Any news here?

Also see #346.

**Comment by ekeyte** [comment]
@localheinz If the PHPUnit version is older, the php-vcr test listener that gets setup needs to be on an older version, but on the newer version, we needed to bump the version. Admittedly, I said I would do some research, and then didn't. But the problem is that I don't know how best to conditionally load the correct test listener in the phpunit.xml.dist file at runtime.

**Comment by ekeyte** [comment]
@uuf6429 It looks like the build still fails.

I don't think we can make any changes or upgrades to the library versions... it looks like #346 will fix the issue with compatibility with PHP 7.1+ though the build fails for some weird OS reason.

I think we should close my PR and move forward with that one. I think I got too ambitious.

**Comment by uuf6429** [comment]
I stand corrected (and updated my previous comment). [PHPUnit 6.x indeed requires PHP 7](https://github.com/sebastianbergmann/phpunit/blob/6.0/composer.json#L23).

**Comment by ekeyte** [comment]
@uuf6429 No worries, it was worth a shot. 

I'm running into too many issues trying to get all the versions to resolve and play together. I've reverted all changes to composer.json, and left it at PHPUnit ~4.4. Seeing how it does now.

CC: @localheinz

**Comment by uuf6429** [comment]
To fix the test listener issue, you can use the same concept I mentioned before:
`CommonVcrListener.php`:
```php
if (class_exists(\VCR\PHPUnit\TestListener\VCRTestListener::class)) {
    // PHPUnit 6+
    class CommonVcrListener extends \VCR\PHPUnit\TestListener\VCRTestListener
    {
    }
} elseif (class_exists(\PHPUnit_Util_Log_VCR::class)) {
    // PHPUnit 5
    class CommonVcrListener extends \PHPUnit_Util_Log_VCR
    {
    }
} else {
    throw new RuntimeException('Unsupported PHPUnit VCR version');
}
```
and `phpunit.xml.dist`:
```xml
    <listeners>
        <listener class="CommonVcrListener"/>
    </listeners>
```

**Comment by ekeyte** [comment]
@uuf6429 Ah yes, I'm now reminded by the failing PHP 7.2 build why we needed to upgrade PHPUnit. `each()` function in PHP has been deprecated and is throwing build errors.

Thanks by the way for the suggestion with the Common. I was thinking of using a decorator instead, and in my tunnelvision didn't even think about extending the existing classes. Jesus. 

I pushed up two commits forgetting to fix the phpunit version and the VCR listener version, but gonna let it rip and see what happens.

**Comment by ekeyte** [comment]
@uuf6429 I'm out of ideas. Latest build is not working.

**Comment by ekeyte** [comment]
@uuf6429 That's a good catch, mate. Thanks for looking into that and finding that issue.

I seem to recall running into this same issue at one of my earlier attempts, and unsure of what to do to fix it. I'm a bit inexperienced when it comes to managing open-source software libraries. Thanks for your help and for opening the issue with php-vcr.

I'll follow that and hopefully we'll be able to get this resolved.

**Comment by renatomefi** [comment]
@ekeyte please use vcr listener 3.1+ and the problem should be solved! This is due to 3.0 being php 7.0 and 3.1 php 7.1 thus allowing php unit to upgrade

**Comment by ekeyte** [comment]
@renatomefi For the `php-vcr/phpunit-testlistener-vcr` package, using the caret would really only be completely safe if they're Semver, right? I did open it up a bit. I made the change that you recommended, but the build seemed to fail for every platform/php version. I'm not really sure how to proceed. Check out this commit: https://github.com/wsdl2phpgenerator/wsdl2phpgenerator/pull/333/commits/221ef8f3d6e893b1cc15c6d13e0c24cb257d069a

**Comment by uuf6429** [comment]
@ekeyte I've got some fixes for `php-vcr/phpunit-testlistener-vcr`... when that's done, the version constraint should look like `"php-vcr/phpunit-testlistener-vcr": "^1.1.8 | ^3.0.1 | ^3.1.1"`

**Comment by ekeyte** [comment]
@uuf6429 Nice! Are they pretty responsive?

Thank you guys for all your help. I'm very new to open-source software, and handling versions for libraries. It's been a great learning experience, especially with all this Composer package resolution stuff.

**Comment by j3rrey** [comment]
When are the fixes going to be merged ?

**Comment by ekeyte** [comment]
Still waiting on this: https://github.com/php-vcr/phpunit-testlistener-vcr/issues/31

**Comment by gisostallenberg** [comment]
Fixed in #386. Thanks for your effort @ekeyte

**Pull request closed without merging**
