### PR TITLE
Generate a SOAPServer Class also #122

### PR DESCRIPTION
**Pull request by tbl0605**
Hi,
here is a patch that should address the issue of the missing class for the SOAP Server part (issue #122).
But unlike what suggested @kasperg, I didn't create a getter for the ClientService::$classmap variable, because I wanted to avoid potential method name collision when the wsdl file has a 'classmap' operation.

Thierry.

### CODE REVIEW

**Comment by kasperg** [comment]
Thanks for the suggestion @tbl0605.

I agree that this is a much better approach for handling a SoapServer class. I am going to go though this as soon as possible but what strikes me immediately is that there are no unit tests. Can you provide this?

**Comment by tbl0605** [comment]
Hi @kasperg,
you're right, I should have added some unit tests firstly, sorry.
I reworked my patch, and made some unit tests ... but I can't get them to work!
Except when I start my new unit test manually of course...
Problem is that the library VCR somehow rewrites the class path of the dynamically generated test classes (using eval()) :
PHP Fatal error:  Class 'VCR\Util\SoapClientTest\TestAbstractServerService' not found in /home/scrutinizer/build/tests/src/Unit/ServerServiceTest.php(74) : eval()'d code on line 1

Even at home, and without this patch, I get following error:
Fatal error: Class 'VCR\Util\SoapClient' not found in C:\myPHPlibs\vendor\wsdl2phpgenerator\wsdl2phpgenerator\vendor\php-vcr\php-vcr\src\VCR\Util\SoapClient.php on line 12

I'm stuck and some help would be welcome :) If you have a solution, I will implement it in my patch.

Thank you!

**Comment by kasperg** [comment]
I'll see what I can do.

**Comment by tbl0605** [comment]
Thank you very much for your help @kasperg!

**Comment by tbl0605** [comment]
Hi @kasperg ,
some news about this one?

Thierry.

**Comment by kasperg** [comment]
@tbl0605 I am afraid not. I have not had time to look further into this issue.

**Comment by tbl0605** [comment]
Hi @kasperg,
I've redone my patch and this time it builds correctly on my side and on github!
I've solved my main problem with the library VCR (under Windows 7) using some suggestion from @b01 taken at https://github.com/php-vcr/php-vcr/issues/67 (php-vcr unit test fail on Windows 7).
I've modified (under Windows) the beginning of the file vendor\php-vcr\php-vcr\src\VCR\Util\SoapClient.php : 
use VCR\LibraryHooks\SoapHook,
    VCR\VCRFactory,
    \SoapClient as PHPSoapClient;

Apparently it's only a problem under Windows, since there's no problem under github.

Could you now have a look at my patch for integration?

Thank you!

Thierry.

**Comment by kasperg** [comment]
Sounds great @tbl0605. I will take a look at the code as soon as possible.

**Comment by tbl0605** [comment]
Hi @kasperg,
I rebased my changes on master, but in a separate pull request #254

**Comment by kasperg** [comment]
Great. I will close this then.

**Pull request closed without merging**
